apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: s66
            - name: DB_PORT
              value: '3306'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-auth
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-auth
                  key: password
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
            - name: api-storage
              mountPath: /api/data
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: api-storage
          persistentVolumeClaim:
            claimName: api-pv-claim
