apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis
spec:
  version: "4.0-v2"
  storageType: Durable
  storage:
    storageClassName: {{ .Values.redis.storageClassName }}
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
